ALTER TABLE ChatAgreements
    ADD WarnLimit INTEGER NOT NULL
    CONSTRAINT D_ChatAgreements_WarnLimit --When Omitted a Default-Constraint Name is autogenerated.
    DEFAULT (2) --Optional Default-Constraint.
            WITH VALUES --Add if Column is Nullable and you want the Default Value for Existing Records.